
    create table images (
        display_order integer not null,
        height_px integer,
        is_primary boolean not null,
        width_px integer,
        created_at timestamp(6) not null,
        furniture_id bigint not null,
        id bigint generated by default as identity,
        size_bytes bigint,
        updated_at timestamp(6),
        mime_type varchar(100),
        url varchar(500) not null,
        alt_text varchar(255),
        name varchar(255) not null,
        primary key (id)
    );
